apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: myapp
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: myapp
        image: myapp:latest
        env:
        - name: ENV
          value: dev
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
