apiVersion: v1
kind: Pod
metadata:
  namespace: myapp
  name: my-app
  labels:
    app: my-app
spec:
  containers:
    - name: my-app
      image: myapp:latest
      env:
      - name: ENV
        value: dev
      imagePullPolicy: IfNotPresent
      ports:
        - name: flask
          containerPort: 5000
          protocol: TCP
